[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules']
remappings = [
    '@gnosis.pm/=node_modules/@gnosis.pm/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'hardhat/=node_modules/hardhat/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config